services:
  app1:
    build: .
    environment:
      - APP_NAME=app1
      - DB_HOST=db
      - DB_NAME=meubanco
      - DB_USER=meuusuario
      - DB_PASS=minhasenha
    networks:
      - backend
    expose:
      - "9000"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 400M

  app2:
    build: .
    environment:
      - APP_NAME=app2
      - DB_HOST=db
      - DB_NAME=meubanco
      - DB_USER=meuusuario
      - DB_PASS=minhasenha
    networks:
      - backend
    expose:
      - "9000"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 400M

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: meubanco
      POSTGRES_USER: meuusuario
      POSTGRES_PASSWORD: minhasenha
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 400M

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - app1
      - app2
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 100M

volumes:
  pgdata:

networks:
  backend:
